services:
  opentenbase-dev:
    platform: linux/amd64
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: opentenbase-dev-container
    user: "root"
    command: /data/project/OpenTenBase/entrypoint.sh
    volumes:
      - .:/data/project/OpenTenBase:cached
      - opentenbase-nodes:/data/nodes
    ports:
      - "30004:30004"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

volumes:
  opentenbase-nodes: