# Plan A - 终极决战版 docker-compose.yml
services:
  opentenbase-dev:
    platform: linux/amd64
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: opentenbase-dev-container
    
    # 关键：以 root 用户身份启动容器
    user: "root"
    
    command: /data/project/OpenTenBase/entrypoint.sh
    
    # 挂载源码和集群数据
    volumes:
      - .:/data/project/OpenTenBase:cached
      - opentenbase-nodes:/data/nodes
    
    ports:
      - "30004:30004"
      
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

volumes:
  opentenbase-nodes: